
#player_names = ["Matt", "Will", "Mike", "Dani", "Rose", "Michelle", "Tom", "Chris", "JB", "Angus", "Jack", "Steve", "Liz", "Ben", "Alex", "Sam", "Rob", ]



# Player.create(username: Faker::Name.first_name)
# Player.create(username: Faker::Name.first_name)
# Player.create(username: Faker::Name.first_name)
# Player.create(username: Faker::Name.first_name)
# Player.create(username: Faker::Name.first_name)
# Player.create(username: Faker::Name.first_name)
# Player.create(username: Faker::Name.first_name)
# Player.create(username: Faker::Name.first_name)
# Player.create(username: Faker::Name.first_name)
# Player.create(username: Faker::Name.first_name)

20.times do
    Robot.create(name: Faker::Games::Pokemon.name, player_id: rand(1..10))
end
# Robot.create(name: Faker::Games::Pokemon.name, player_id: 2)
# Robot.create(name: Faker::Games::Pokemon.name, player_id: 3)
# Robot.create(name: Faker::Games::Pokemon.name, player_id: 4)
# Robot.create(name: Faker::Games::Pokemon.name, player_id: 5)
# Robot.create(name: Faker::Games::Pokemon.name, player_id: 1)
# Robot.create(name: Faker::Games::Pokemon.name, player_id: 2)
# Robot.create(name: Faker::Games::Pokemon.name, player_id: 3)
# Robot.create(name: Faker::Games::Pokemon.name, player_id: 2)
# Robot.create(name: Faker::Games::Pokemon.name, player_id: 6)
# Robot.create(name: Faker::Games::Pokemon.name, player_id: 1)
# Robot.create(name: Faker::Games::Pokemon.name, player_id: 2)
# Robot.create(name: Faker::Games::Pokemon.name, player_id: 3)
# Robot.create(name: Faker::Games::Pokemon.name, player_id: 4)
# Robot.create(name: Faker::Games::Pokemon.name, player_id: 5)
# Robot.create(name: Faker::Games::Pokemon.name, player_id: 1)
# Robot.create(name: Faker::Games::Pokemon.name, player_id: 2)
# Robot.create(name: Faker::Games::Pokemon.name, player_id: 3)
# Robot.create(name: Faker::Games::Pokemon.name, player_id: 2)
# Robot.create(name: Faker::Games::Pokemon.name, player_id: 6)

# player10 = Player.create()

# battle1 = Battle.create()
# battle2 = Battle.create()
# battle3 = Battle.create()
# battle4 = Battle.create()
# battle5 = Battle.create()
# battle6 = Battle.create()
# battle7 = Battle.create()
# battle8 = Battle.create()

# batrob1 = BatRob.create(hitpoints: 100)
# batrob2 = BatRob.create(hitpoints: 100)
# batrob3 = BatRob.create(hitpoints: 100)
# batrob4 = BatRob.create(hitpoints: 100)
# batrob5 = BatRob.create(hitpoints: 100)
# batrob6 = BatRob.create(hitpoints: 100)
# batrob7 = BatRob.create(hitpoints: 100)
# batrob8 = BatRob.create(hitpoints: 100)
# batrob9 = BatRob.create(hitpoints: 100)
# batrob10 = BatRob.create(hitpoints: 100)
# batrob11 = BatRob.create(hitpoints: 100)
# batrob12 = BatRob.create(hitpoints: 100)
# batrob13 = BatRob.create(hitpoints: 100)
# batrob14 = BatRob.create(hitpoints: 100)
# batrob15 = BatRob.create(hitpoints: 100)
# batrob16 = BatRob.create(hitpoints: 100)
# batrob17 = BatRob.create(hitpoints: 100)
# batrob18 = BatRob.create(hitpoints: 100)
# batrob19 = BatRob.create(hitpoints: 100)
# batrob20 = BatRob.create(hitpoints: 100)
# batrob21 = BatRob.create(hitpoints: 100)
# batrob22 = BatRob.create(hitpoints: 100)
# batrob23 = BatRob.create(hitpoints: 100)
# batrob24 = BatRob.create(hitpoints: 100)


