
#player_names = ["Matt", "Will", "Mike", "Dani", "Rose", "Michelle", "Tom", "Chris", "JB", "Angus", "Jack", "Steve", "Liz", "Ben", "Alex", "Sam", "Rob", ]

# player1 = Player.new(name: Faker::Name.first_name)
# player2 = Player.new(name: Faker::Name.first_name)
# player3 = Player.new(name: Faker::Name.first_name)
# player4 = Player.new(name: Faker::Name.first_name)
# player5 = Player.new(name: Faker::Name.first_name)
# player6 = Player.new(name: Faker::Name.first_name)
# player7 = Player.new(name: Faker::Name.first_name)
# player8 = Player.new(name: Faker::Name.first_name)
# player9 = Player.new(name: Faker::Name.first_name)
# player10 = Player.new()

# battle1 = Battle.new()
# battle2 = Battle.new()
# battle3 = Battle.new()
# battle4 = Battle.new()
# battle5 = Battle.new()
# battle6 = Battle.new()
# battle7 = Battle.new()
# battle8 = Battle.new()

# batrob1 = BatRob.new(hitpoints: 100)
# batrob2 = BatRob.new(hitpoints: 100)
# batrob3 = BatRob.new(hitpoints: 100)
# batrob4 = BatRob.new(hitpoints: 100)
# batrob5 = BatRob.new(hitpoints: 100)
# batrob6 = BatRob.new(hitpoints: 100)
# batrob7 = BatRob.new(hitpoints: 100)
# batrob8 = BatRob.new(hitpoints: 100)
# batrob9 = BatRob.new(hitpoints: 100)
# batrob10 = BatRob.new(hitpoints: 100)
# batrob11 = BatRob.new(hitpoints: 100)
# batrob12 = BatRob.new(hitpoints: 100)
# batrob13 = BatRob.new(hitpoints: 100)
# batrob14 = BatRob.new(hitpoints: 100)
# batrob15 = BatRob.new(hitpoints: 100)
# batrob16 = BatRob.new(hitpoints: 100)
# batrob17 = BatRob.new(hitpoints: 100)
# batrob18 = BatRob.new(hitpoints: 100)
# batrob19 = BatRob.new(hitpoints: 100)
# batrob20 = BatRob.new(hitpoints: 100)
# batrob21 = BatRob.new(hitpoints: 100)
# batrob22 = BatRob.new(hitpoints: 100)
# batrob23 = BatRob.new(hitpoints: 100)
# batrob24 = BatRob.new(hitpoints: 100)


